name: Build EXE & Create Release

on:
  workflow_dispatch:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      # ۱. Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # ۲. نصب Python 3.11
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # ۳. نصب وابستگی‌ها
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pyinstaller

      # ۴. خواندن متغیر VERSION از main.py
      - name: Extract Version
        id: get_version
        run: |
          $version = Select-String -Pattern 'VERSION\s*=\s*"(.*?)"' -Path "./main.py" | ForEach-Object { $_.Matches.Groups[1].Value }
          Write-Host "Detected version: $version"
          echo "version=$version" >> $env:GITHUB_OUTPUT

      # ۵. ذخیره متغیر version.txt مطمئن‌تر
      - name: Save version to file
        run: |
          echo "${{ env.version }}" > version.txt
          cat version.txt
          if [ -z "${{ env.version }}" ]; then
            echo "Error: Version variable is empty!"
            exit 1
          fi

      # ۶. ذخیره `version.txt` به عنوان artifact
      - name: Upload version as artifact
        uses: actions/upload-artifact@v4
        with:
          name: version
          path: ./version.txt

      # ۷. ساخت فایل EXE با PyInstaller
      - name: Build with PyInstaller
        run: |
          pyinstaller --noconfirm --onefile --windowed --icon "./assets/icon.ico" --name "PhotoSlicer v${{ env.version }}" --add-data "engine.py;." --add-data "./assets;assets/" "./main.py"
      
      # ۸. ذخیره EXE به Artifact
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: photo_slicer_build
          path: ./dist/
