name: Build EXE & Create Release

on:
  workflow_dispatch:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      # ۱. Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # ۲. نصب Python 3.11
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # ۳. نصب وابستگی‌ها
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pyinstaller

      # ۴. خواندن متغیر VERSION از main.py
      - name: Extract Version
        id: get_version
        run: |
          $version = Select-String -Pattern 'VERSION\s*=\s*"(.*?)"' -Path "./main.py" | ForEach-Object { $_.Matches.Groups[1].Value }
          if ($version) {
            echo "version=$($version)" >> $GITHUB_OUTPUT
            Write-Host "Extracted version: $($version)"
          } else {
            Write-Host "No version found"
            exit 1
          }

      # ۵. ذخیره EXE با PyInstaller
      - name: Build with PyInstaller
        run: |
          pyinstaller --noconfirm --onefile --windowed --icon "./assets/icon.ico" --name "PhotoSlicer v${{ steps.get_version.outputs.version }}" --add-data "engine.py;." --add-data "./assets;assets/" "./main.py"

      # ۶. ذخیره EXE به Artifact
      - name: Upload EXE Artifact
        uses: actions/upload-artifact@v4
        with:
          name: photo_slicer_build
          path: ./dist/

  release:
    needs: build
    runs-on: windows-latest
    steps:
      # ۰.۵. دانلود متغیر نسخه از Artifact
      - name: Download version artifact
        uses: actions/download-artifact@v4
        with:
          name: version
          path: ./version

      # ۰.۶. خواندن متغیر VERSION
      - name: Read version from file
        id: read_version
        run: |
          $version = Get-Content -Path "./version"
          echo "version=$version" >> $GITHUB_OUTPUT
          Write-Host "Version read from artifact: $version"

      # ۷. ایجاد Release
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: v${{ steps.read_version.outputs.version }}
          release_name: Release v${{ steps.read_version.outputs.version }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # ۸. دانلود EXE از Artifact
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: photo_slicer_build
          path: ./dist/

      # ۹. آپلود EXE به Release
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/PhotoSlicer.exe
          asset_name: PhotoSlicer.exe
          asset_content_type: application/octet-stream
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
